# Generated by Django 4.1.7 on 2023-05-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
