# Generated by Django 4.1.7 on 2023-04-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_customer_customerprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='logo',
            field=models.ImageField(upload_to='media/designer/logo'),
        ),
    ]
