# Generated by Django 4.1.7 on 2023-04-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_designer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/designer/logo'),
        ),
    ]
