# Generated by Django 4.1.7 on 2023-04-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_designer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='bio',
            field=models.TextField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='designer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/designer/logo'),
        ),
    ]
