# Generated by Django 4.1.7 on 2023-04-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_designer_logo'),
        ('designers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.designer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(upload_to='media/product_images/'),
        ),
    ]
